### PR TITLE
Fix Cert title & store address for ITE

### PR DESCRIPTION
**Pull request by Pat-Goh**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [ ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [ ] No more than 5 templates or 25 added/modified files in the pull request
- [ ] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by rjchow** [comment]
What happened to your previous cert store address?

All cert store changes must now go through an application process located at: https://form.gov.sg/5cd5141c02d207001007e322

**Comment by Pat-Goh** [comment]
The previous cert store address was provided wrongly by the user.  This correct address had already been submitted to Shiya by our user manager.  We will proceed to submitted the form as required.  Thanks.

**Comment by rjchow** [comment]
Oh it's been submitted? I'll just confirm that and merge this PR once that is done - thanks

**Comment by Pat-Goh** [comment]
I have just submitted the form, just in case.  Apologies for the trouble caused.

**Comment by Pat-Goh** [comment]
Thanks for the deployment.
However, when I displayed the cert file in production viewer, there will be a warning showing 'Institution not in our registry' but it was ok in the preview viewer (Organisation Name should be 'Institute of Technical Education').  Please assist, thanks.

image
image

**Comment by yehjxraymond** [comment]
The preview uses the registry data in ropsten while the actual site uses the main net. Make sure you have the registry updated in main net as well. Open a separate PR for that.

**Comment by yehjxraymond** [comment]
To Ensure it works on prod, use the production preview instead.

**Comment by Pat-Goh** [comment]
The production preview was used and it was ok with Certificate Verified correctly but on production site, https://opencerts.io/, it was not ok and showed the warning of 'Institution not in our registry'. Please help and let me know of any required follow-up action.  Thanks.

**Comment by Pat-Goh** [comment]
I just notice that static/registry.json was updated with some new details after my merge but it reflected our old cert store address and a different email address from the information sent by our user manager to Shiya.  
"0x908595e0B09Fb2d5950eCD196695490E211A6d4d": {
      "name": "Institute of Technical Education",
      "displayCard": true,
      "website": "https://www.ite.edu.sg/",
      "email": "ithelpdesk@ite.edu.sg",
      "phone": "1800-2222 111",
      "logo": "/static/images/ITE_logo.png",
      "id": "ite-registry"
    },
[Registry_v2.0_ITE_revised.xlsx](https://github.com/OpenCerts/opencerts-website/files/3283796/Registry_v2.0_ITE_revised.xlsx)

Please assist use to update your latest changes to reflect our correct cert store & email addresses, thanks.
cert store: 0x0CE38eBEa3B943Ee6DA24163710b25Ef8654f39E
email: training@ite.edu.sg

**Comment by rjchow** [comment]
Sorry about that, the updated info got overwritten by mistake when I was merging another pull request yesterday - can you check that this is correct? https://github.com/OpenCerts/opencerts-website/pull/336 
will merge right away

**Comment by Pat-Goh** [comment]
It is ok in production preview #336, thanks for your quick response.

**Comment by rjchow** [comment]
merged

**Pull request merged**
