### PR TITLE
Template/tp ftcerts

### PR DESCRIPTION
**Pull request by rjchow**
Split TP's PR out into the FT certs first along with the common files
Did not make any changes to the code except for lint fix

@khunshwephyo please review this and i'll merge it

### CODE REVIEW

**Comment by rjchow** [comment]
following this you can either merge master into your PR branch or do a rebase to clean up the commit history, that'll leave just the PT certs there and you can take the time to fix them as you need

**Comment by khunshwephyo** [comment]
> 
> 
> Split TP's PR out into the FT certs first along with the common files
> Did not make any changes to the code except for lint fix
> 
> @khunshwephyo please review this and i'll merge it

Hi, I have reviewed and tested.  Okay to merge.  Thank you so much!

**Comment by khunshwephyo** [comment]
> 
> 
> following this you can either merge master into your PR branch or do a rebase to clean up the commit history, that'll leave just the PT certs there and you can take the time to fix them as you need

I will follow up on this.  Thanks again.

**Comment by rjchow** [comment]
i made some minor changes to pass the code duplication check, do refactor it properly later on

**Comment by khunshwephyo** [comment]
> 
> 
> i made some minor changes to pass the code duplication check, do refactor it properly later on
> (it's merged now, have a check on opencerts.io)

Thank you so much!  I have checked and able to preview TP certificates and transcripts on https://opencerts.io.   I will follow up with refactoring.

**Pull request merged**
