### PR TITLE
Register SIPMM Institute in registry.json & add New Templates

### PR DESCRIPTION
**Pull request by raulgomezc**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''"
---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Certificate Template 
- [x] No more than 5 templates or 25 added/modified files in the pull request
- [x] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [x] Sample certificate file included for each template, located alongside the integration test for each template
- [x] Sample certificates must obviously be a sample certificate
  - [x] Obviously fictitious name
  - [x] Obviously sample signatory images
- [x] No fixed-size raster images as part of certificate layout
- [x] Mobile responsive design
- [x] Date parsing should be localised to template author's timezone
- [x] Webpack chunking code is correct
  - [x] Has chunking code
  - [x] Same chunking code as the other certificates belonging to that institute
- [x] Certificate Store Addresses have been updated
  - [x] Template Whitelist
  - [x] Registry
- [x] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### Pre-merge checks

- [x] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [x] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [x] `npm run test` passes
- [x] `npm run test:integration` passes
- [x] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### CODE REVIEW

**Comment by raulgomezc** [comment]
Hey @rjchow ,

This is ready for review, please take a look when you get a chance.

**Comment by sipmm-sg** [comment]
@rjchow thanks for your help on looking into this. I see that you added pending for SSG decision. Please let us know if there is anything else required. - Singapore Institute of Purchasing and Materials Management (SIPMM)

**Comment by raulgomezc** [comment]
Hey @rjchow, any updates on this?

**Comment by rjchow** [comment]
Please submit your application to be added to the registry using this form: https://form.gov.sg/5cd5141c02d207001007e322

**Comment by sipmm-sg** [comment]
> Please submit your application to be added to the registry using this form: https://form.gov.sg/5cd5141c02d207001007e322

Hi @rjchow, thanks for informing us. We have submitted the form. Please let us know if you require any further information. Have a great day ahead.

**Comment by raulgomezc** [comment]
Hey, @rjchow can you please update us with the status on this?

**Comment by izy100** [comment]
You may follow up with toh_swee_chien@ssg.gov.sg. Please inform him that you are not getting a response after submitting the form.

**Comment by raulgomezc** [comment]
Hey @rjchow and @izy100 could you please update us on the state of the request? This PR has 4 months open and ready for review, you changed the structure of the project and told us to put up a request but we have received no response.

**Comment by izy100** [comment]
Did toh_swee_chien@ssg.gov.sg reply to you?

**Comment by raulgomezc** [comment]
No, he hasn't replied.

**Comment by yehjxraymond** [comment]
SSG side did not allow us to merge this in because you are not part of the approved list. Two suggestions:

1. Contact SSG again. or
2. Use version 2. It was created specifically for such cases.

**Comment by raulgomezc** [comment]
Can you point me to where version 2 is at?

**Comment by yehjxraymond** [comment]
https://docs.opencerts.io/

Under TOC, you will see the section on v2. Broadly, you will just need to deploy your own independent document renderer and then reflect that in the certificate you issue so that our site knows where to fetch the visuals from.

**Comment by yehjxraymond** [comment]
Closing this PR. You will not need to raise any PR for v2 method.

Alternatively, if you've got approval from SSG you may migrate the code to legacy-templates and create a PR there.

**Pull request closed without merging**
