### PR TITLE
Added 5 Templates for SSG : QUAL

### PR DESCRIPTION
**Pull request by ssgwsg-acn**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Certificate Template 
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### Pre-merge checks

- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### CODE REVIEW

**Comment by ssgwsg-acn** [comment]
When i am trying to to create pull request its adding all the previous commits as well in the pull request. also if i commit another 5 templates then it will push to same pull request. how can we add multiple PR request at same time with different commits.

**Comment by rjchow** [comment]
use branches
https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by rjchow** [comment]
closed because PR exceeds 5 templates or 25 files

**Comment by ssgwsg-acn** [comment]
So you want us to checkout new branch from out master and add max 5 templates and commit it, and raise the pull request. same way every time create new branch from master and pull request

**Comment by rjchow** [comment]
Yes the idea is that I cannot possibly give proper feedback on 80+ files at
a time. If the differences are minor and have no issues it will go quickly

**Comment by ssgwsg-acn** [comment]
Spiting is causing issue with our code. can you check by commits and approve the request,  because we have one more day to go live.

**Comment by rjchow** [comment]
splitting isn't causing issues with your code, you just need to learn how git works
looking at your commits don't help either, you have over 50 of those in this PR because your git state is all messed up

please create a smaller PR with your most important changes that you need by tomorrow.

**Pull request closed without merging**
