### PR TITLE
Add PET CET DPLUS certificate

### PR DESCRIPTION
**Pull request by RP-OIS-SK**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [Y ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [ Y] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [Y ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [Y ] `npm run test` passes
- [ Y] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [Y] No more than 5 templates or 25 added/modified files in the pull request
- [Y] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [Y] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [Y] Sample certificate file included for each template, located alongside the integration test for each template
- [Y] Sample certificates must obviously be a sample certificate
  - [Y] Obviously fictitious name
  - [Y] Obviously sample signatory images
- [Y] No fixed-size raster images as part of certificate layout
- [Y] Mobile responsive design
- [Y] Date parsing should be localised to template author's timezone
- [Y] Webpack chunking code is correct
  - [Y] Has chunking code
  - [Y] Same chunking code as the other certificates belonging to that institute
- [Y] Certificate Store Addresses have been updated
  - [Y] Template Whitelist
  - [Y] Registry
- [Y] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by RP-OIS-SK** [comment]
Hi, 

Is this pull request processed ?

**Comment by rjchow** [comment]
no its in the queue

**Comment by RP-OIS-SK** [comment]
Thanks,  hopefully it will be out in the next few days

**Comment by rjchow** [comment]
I assume this obsoletes #251 ?

**Comment by RP-OIS-SK** [comment]
> I assume this obsoletes #251 ?

Yes, you can close #251. 

Thanks

**Pull request merged**
