### PR TITLE
Code change to use number-to-words lib

### PR DESCRIPTION
**Pull request by RP-OIS-SK**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Certificate Template 
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### Pre-merge checks

- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### CODE REVIEW

**Comment by RP-OIS-SK** [comment]
Not sure why it failed in the integration test again. 

On the local machine, it passed the test. 

D:\opencerts-website>npm run integration:headless

> opencerts-website@2.0.0 integration:headless D:\opencerts-website
> npm run build:static && testcafe chrome:headless src/**/*.spec.js --app "npm run serve-static"


> opencerts-website@2.0.0 build:static D:\opencerts-website
> next build && next export

[5:57:17 AM] Compiling server
[5:57:17 AM] Compiling client
> Using external babel configuration
> Location: "D:\opencerts-website\.babelrc"
[5:57:25 AM] Compiled server in 9s
[5:57:27 AM] Compiled client in 10s
> using build directory: D:\opencerts-website\.next
  copying "static" directory
  copying "static build" directory
> exporting path: /
> exporting path: /registry
> exporting path: /privacy
> exporting path: /viewer
> exporting path: /faq
> exporting path: /frameless-viewer

Export successful
 Running tests in:
 - HeadlessChrome 73.0.3683 / Windows 10.0.0

 Default Certificate Template
 √ Default certificate is rendered correctly

 Republic Polytechnic
 √ PET certificate is rendered correctly


 2 passed (29s)

**Comment by yehjxraymond** [comment]
Hey buddy, found the problem, please go to the file `/static/registry.json` and add a new line:

```
{
  "issuers": {
    "0x007d40224f6562461633ccfbaffd359ebb2fc9ba": "Government Technology Agency of Singapore (GovTech)",
    "0xa5d801265D29A6F1015a641BfC0e39Ee3dA2AC76": "Ngee Ann Polytechnic",
    "0x866Fb78aC3c87019aBff9FB566acfF66F75Cfa46": "ROPSTEN: Ngee Ann Polytechnic",
    "0xc36484efa1544c32ffed2e80a1ea9f0dfc517495": "ROPSTEN: Ngee Ann Polytechnic",
    "0x061aFcFF60b90E0F633F8ef157e01BaB9b2FfDD3": "ROPSTEN: Republic Polytechnic",
    "0x24a7DE31D231221ab6B1B325Ca5F1AA7bfbaaabA": "Singapore Institute of Technology",
    "0x897E224a6a8b72535D67940B3B8CE53f9B596800": "ROPSTEN: Singapore Institute of Technology",
    "0x3f43FB8546E97b2c1D5eD087767C0d2eb2e13f8b": "ROPSTEN: Singapore Institute of Technology (Ledger Nano)",
    "0xfEbB273495F5C2c4783E23424Fe9773691b57fcB": "ROPSTEN: National University of Singapore"
  }
}
```

This will remove the invalid issuer notice.

**Comment by yehjxraymond** [comment]
please format the spacing on the registry.json....

**Comment by RP-OIS-SK** [comment]
HI Raymond,

Thank you for pointing out the error.  After the changes in the
registry.json, RP cert have passed the integration test but the NP is
getting a lot of errors.  What to do next ? remove NP folder ?

Thanks and regards,
SK

**Comment by yehjxraymond** [comment]
Great idea if it didnt actually builds fine after it is restarted.

**Comment by yehjxraymond** [comment]
Please format the registry json file to remove the additional spaces.

**Pull request closed without merging**
