### PR TITLE
New certificate for Joint Poly and joint certificate with SUSS. Add Production Certificate Store Address

### PR DESCRIPTION
**Pull request by RP-OIS-SK**
New certificate for Joint Poly and joint certificate with SUSS. Add Production Certificate Store Address

---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Pre-merge checks

- [Y ] Did not modify any files outside of your organisation's template folder (e.g package-lock.json or anything else)
- [Y] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [Y] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [Y] `npm run test` passes
- [Y] `npm run test:integration` passes
- [Y] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### Certificate Template 
- [Y] No more than 5 templates or 25 added/modified files in the pull request
- [Y] Ensure that your .opencert file's data complies with the intentions of the OpenCerts' schema - e.g recipient related information is inside the `recipient` object, etc.
- [Y] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [Y] Sample certificate file included for each template, located alongside the integration test for each template
- [Y ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [Y] No fixed-size raster images as part of certificate layout
- [Y] Mobile responsive design
- [Y] Date parsing should be localised to template author's timezone
- [Y] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [Y] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [Y] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### CODE REVIEW

**Comment by rjchow** [comment]
**[Y] No more than 5 templates or 25 added/modified files in the pull request**

**Comment by RP-OIS-SK** [comment]
HI, 

Not sure why this step "continuous-integration/travis-ci/pr" failed.  How do I correct this ?

**Comment by rjchow** [comment]
you can click on the details link beside the failing step and see what's gone wrong

**Comment by RP-OIS-SK** [comment]
This is the error  "We couldn't find the repository  OpenCerts/opencerts-website"

**Comment by rjchow** [comment]
image

**
PLEASE READ THE PULL REQUEST GUIDELINES.
**
Before even beginning to review your PR there's already two issues
- [Y] No more than 5 templates or 25 added/modified files in the pull request
- [Y] Linter issues resolved (Run npm run lint:fix to see issues)

I will be closing this PR since its obvious you have not read the guidelines

**Comment by RP-OIS-SK** [comment]
I have already submitted all other templates except for the 4 new templates.  Refer to #251.  In this pull request, I have only submit the request for 4 new templates.

**Pull request closed without merging**
