### PR TITLE
add registry and template

### PR DESCRIPTION
**Pull request by laykoonjune**

### CODE REVIEW

**Comment by laykoonjune** [comment]
Please advise why is the check unsuccessful?

**Comment by rjchow** [comment]
have fixed it for you, was missing a comma in the registry.json

**Comment by laykoonjune** [comment]
thanks.

**Comment by laykoonjune** [comment]
I try to test to use a test .opencert file to view my template however I still unable to view it can you help to advise where I went wrong?
[test.zip](https://github.com/OpenCerts/opencerts-website/files/3027930/test.zip)

**Comment by yehjxraymond** [comment]
Closing, obsolete PR.

**Pull request closed without merging**
