### PR TITLE
Add template for IBS in Ropsten

### PR DESCRIPTION
**Pull request by lanlan3322**
Add template for IBS in Ropsten testnet.

### CODE REVIEW

**Comment by yehjxraymond** [comment]
Hi can you also attach a copy of a certificate here for us to test? Thanks

**Comment by lanlan3322** [comment]
Sure, I will upload a certificate once the test is done from our side.

**Comment by lanlan3322** [comment]
> Hi can you also attach a copy of a certificate here for us to test? Thanks

Just added one sample cert.

**Comment by lanlan3322** [comment]
> Hi can you also attach a copy of a certificate here for us to test? Thanks

When can you help to merge IBS into ropsten?
So that we can test our template.
Thanks,

**Comment by yehjxraymond** [comment]
Please approach SSG to get their approval to issue OpenCerts. Will close this PR for now.

**Pull request closed without merging**
