### PR TITLE
NCS: eCert Template for SIT

### PR DESCRIPTION
**Pull request by erwinsg**
NCS: eCert Template for SIT

### CODE REVIEW

**Comment by rjchow** [comment]
erwin the build is failing because the b64 bg image is too big

for two separate reasons I will require you to change the way the template is done

1. having a fixed size bg image means that the cert wont work the same on all screen aspect ratios
2. its highly inefficient to have a monolithic background image as you can see, the certificate.js file is 1mb+

Ideally what I would do is to digitise the design and do it in a vector format in a responsive layout.

If you cannot do that due to stakeholder objections or whatever reasons, slice up the image and set the background to a repeating pattern instead, and split the image up with separate corners, logo, etc components.

**Comment by yehjxraymond** [comment]
You will not want to use a fixed background because if you code it for one screen size, it will look absolutely different on another, and you might have your signature or text covering the red seal.

Instead separate out the:
- background and border
- SIT logo
- rea seal

If you have trouble with the background and border, you may refer to `border-image-slice` to achieve what you want. 

The key idea is to have a small image that can be repeated for the entire document. You can achieve it via a 9-grid image. Below is some useful resources.

Resources:
https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice
https://tympanus.net/codrops/css_reference/border-image-slice/

**Comment by erwinsg** [comment]
hi Rui Jie, Raymond,

I will try it out later.
Thank you.

**Comment by rjchow** [comment]
For reference NP has their cert and transcript templates under 10kb each, with a separate common images file used across all their certs at 600kb.

There's no strict guideline for the size but the build is failing because its timing out on parsing your certificate js file after 10 minutes

**Comment by erwinsg** [comment]
HI Raymond, Rui Jie,

I manage to resolve the conflict, but I am not sure how to proceed.
Can please advise whether I can use SourceTree to merge to https://github.com/OpenCerts/opencerts-website? Thank you.

Below is the screen capture 
image

**Comment by erwinsg** [comment]
Hi Raymond, Rui Jie,

Sorry for multiple comment.
I manage to merge as per below screen capture. Can I push it to https://github.com/OpenCerts/opencerts-website? Thank you.

image

**Comment by rjchow** [comment]
Send me a sample certificate using email I'll assist

**Comment by rjchow** [comment]
Three issues so far with the code

1) linter was unhappy, should have taken care of that via `yarn lint:fix` to clear up the issues that can be cleared automatically and resolved the outstanding issues manually (I've done this for you)

2) there's commented code (I've removed this for you)

3) you're still using a fixed background -- please follow raymond's resources on how to do the 9-cell layout

4) you have signature images in your template -- we've recommended NP not to do this as it makes your signatories's signature images very very public, so I would recommend you put it in your certificate file as well.

Please resolve 3) and 4) before we proceed

**Comment by rjchow** [comment]
image

In the meantime feel free to use this preview feature to show your stakeholders what it looks like

**Comment by erwinsg** [comment]
For item 3, i had some difficulties as the border and background is not the same, how can i slice up as per suggested?

**Comment by rjchow** [comment]
sit cert bg

for the corners (1-4) you keep them as is
for 5 and 7 you truncate the image so that it is just 1 segment which can be repeated horizontally
8 and 6 the same except vertically
9 truncate it so that it can be tiled

Then you save it as one image, measure the offsets and apply the css border-image rule accordingly
The end result should be a much smaller image that can be tailored for whatever size/aspect necessary according to the user's device.

https://css-tricks.com/understanding-border-image/ and
http://www.norabrowndesign.com/css-experiments/border-image-anim.html

should be helpful

**Comment by erwinsg** [comment]
Thanks for your guide Rui Jie.

After the template was changed, I noted that due to the grainy texture background, the color in some parts of the cert is slightly different.

**Comment by erwinsg** [comment]
Rui Jie, yes, i did close by accident, how to re-open ar?

**Comment by rjchow** [comment]
I can't really see what's in the picture you linked but you'll need to slice the original image so that the patterns line up and tile properly

**Comment by erwinsg** [comment]
Hi Rui Jie, Raymond,

I managed to update the templates to a nicer background. Can you help me check on my revised codes? I have sent to your emails CHOW_Ruijie@tech.gov.sg and Raymond_YEH@tech.gov.sg.

Thank you.

**Comment by yehjxraymond** [comment]
Have you push to this branch?

**Comment by yehjxraymond** [comment]
Erwin,

No you may not push code directly to the master branch. This is prevent any unfinished features and bugs to go into the currently deployed version. Even we as the main maintainers do not have access to push directly to the master branch.

You may try to resolve the merge conflict of if you prefer to start from a clean slate, you may do the following:

1. Ditch your current branch
2. Pull the latest change from our master
3. Add in the change
4. Make a PR back to our master

If for any reason you need to see how it looks like in production, please use the netlify deployment from the `checks` when you perform a PR.

**Comment by erwinsg** [comment]
Hi Raymond,

My latest code is in, but there is error. Can please advise?
thanks

**Comment by rjchow** [comment]
As mentioned earlier you need to run lint fix

**Comment by erwinsg** [comment]
hi Rui Jie,

Do you have guide to init the eslint?

**Comment by rjchow** [comment]
`yarn lint:fix`

**Comment by yehjxraymond** [comment]
image

Erwin, your cert you've sent us earlier is not working. Can you please send another?

**Comment by erwinsg** [comment]
hi Raymond,

The store id is updated to the one given by SIT, so I could not generate it using the store id given by them. Let me update and commit using the store id that i test in my local, and after you complete updating it, i will update it with their store id.

thank you.

**Comment by erwinsg** [comment]
The store id has been updated to the one that I tested in my local. After you completed verifying it, I will update it to the store id given by SIT for their UAT.
Please assist to verify.

**Comment by yehjxraymond** [comment]
screen shot 2018-12-11 at 10 28 25 am
screen shot 2018-12-11 at 10 34 05 am

Looking great on both desktop and mobile view!

Erwin, the allowed address can be an array, so if you like to have two address in it also possible. At the end of the day we will only whitelist one address (even if you have two) to get past the yellow warning box. You may revert the address to the prod one or add both in.

**Comment by yehjxraymond** [comment]
Once that is done, we will proceed to merge this code in.

**Comment by erwinsg** [comment]
hi Raymond,

I have just merged in with 2 store addresses.
Many thanks for your support and also Rui Jie.

:)

Please let us know again once user can start UAT.

**Comment by yehjxraymond** [comment]
Hi Erwin,

Your code change has been merged in. It will be automatically deployed to both opencerts.io and dev.opencerts.io. 

Can I confirm with you that the PRODUCTION contract store address for SIT will be `0x897E224a6a8b72535D67940B3B8CE53f9B596800`? This will be added to the list of whitelisted institutes and the warning message will be removed for certificates issued from that store.

**Comment by erwinsg** [comment]
hi Raymond,

From what I know, this store address is only for UAT, as they used Metamask to create the store.
There will be another address for Production.

**Comment by erwinsg** [comment]
hi Raymond,

I can't seem to view it on opencerts.io, but i can view it on dev.opencerts.io

Can I ask user to test using dev.opencerts.io?

**Comment by rjchow** [comment]
yes

**Pull request merged**
