### PR TITLE
 Added SOA Templates(SFSOA001,SFSOAES001,SOAES001,SOAReprint,SOASV001)

### PR DESCRIPTION
**Pull request by ssgwsg-acn**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Certificate Template 
- [ ] No more than 5 templates or 25 added/modified files in the pull request
- [ ] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [ ] Sample certificate file included for each template, located alongside the integration test for each template
- [ ] Sample certificates must obviously be a sample certificate
  - [ ] Obviously fictitious name
  - [ ] Obviously sample signatory images
- [ ] No fixed-size raster images as part of certificate layout
- [ ] Mobile responsive design
- [ ] Date parsing should be localised to template author's timezone
- [ ] Webpack chunking code is correct
  - [ ] Has chunking code
  - [ ] Same chunking code as the other certificates belonging to that institute
- [ ] Certificate Store Addresses have been updated
  - [ ] Template Whitelist
  - [ ] Registry
- [ ] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### Pre-merge checks

- [ ] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [ ] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [ ] `npm run test` passes
- [ ] `npm run test:integration` passes
- [ ] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### CODE REVIEW

**Comment by ssgwsg-acn** [comment]
Please note we have committed only 5 templates in request too, but as there are merge conflict with previous index.js, this branch is updated from Master so showing more files changed.

**Comment by ssgwsg-acn** [comment]
Problem is if i dont merge then it show conflict, if i merge the total file will get increase as it not approved previous pull and get merged.

**Comment by rjchow** [comment]
resolved the conflict for you, can you double check that it is correct?

**Comment by ssgwsg-acn** [comment]
Ya fine, as long is this file is common for all templates it will have merge conflict. once everything is merged will re confirm that this file didn't miss any template.

**Comment by ssgwsg-acn** [comment]
Appreciate, for your review and merging all these templates

**Comment by ssgwsg-acn** [comment]
One more question we have once this merging is done, it means the code is now in PROD? is there any other step we need to do?, also apart from netlify link can we access this templates via https://dev.opencerts.io or https://opencerts.io

**Comment by rjchow** [comment]
Correct, once it is merged it is in production on OpenCerts.io . No other
steps needed

you will be able to view the certs on there if it's issued using your
production certificate store, or at dev.opencerts.io if it's issued using
your ropsten store

**Comment by ssgwsg-acn** [comment]
Thank you, now we have two open pull request once it merge will test out our certs in dev.opencerts.io.

**Comment by rjchow** [comment]
no qualificationLevel for these?

**Comment by rjchow** [comment]
^

**Comment by ssgwsg-acn** [comment]
We do have qualificationLevel in JSON but not displaying it in template, mostly SOA certs have static qualificationLevel.

**Comment by rjchow** [comment]
it's not in the .opencert files for these last two PRs though

**Comment by ssgwsg-acn** [comment]
As its not using in template can we do one thing. we have some UI fix also for templates, so with those will move the new .opencert file also. is that okay with you

**Comment by rjchow** [comment]
sorry I don't understand, what do you mean?

**Comment by ssgwsg-acn** [comment]
Sorry for the confusion we have updated the opencert files with qualificationLevel

**Comment by ssgwsg-acn** [comment]
SonarCloud Code Analysis is failing because we are committing only opencert files. in that case do you merge pull request. Because this opencert files are sample files.

**Comment by rjchow** [comment]
image

it's not the opencert files, these are 5 different files but they all look the same - do fix this

**Comment by yehjxraymond** [comment]
## Code Duplication
Our scanner automatically catches poor coding practices, including code duplication. Please see how Ngee Ann Poly deal with duplicated code. Most components are reused there.

## Updated Interface
Please also update your MultiCertificateRenderer interface:
1. The interface for `MultiCertificateRenderer` does not require {certificate} to be passed in now.
2. Proptypes can be removed completely.

You may view the certificates in master for reference.

```
// IS OBSELETE
import { MultiCertificateRenderer } from "template-utils/MultiCertificateRenderer";

// IS CORRECT
import MultiCertificateRenderer from "template-utils/MultiCertificateRenderer";

const SOA001 = () => (
  <MultiCertificateRenderer
    templates={templates}
    whitelist={approvedAddresses}
  />
);
```

**Comment by ssgwsg-acn** [comment]
rjchow & yehjxraymond You are introducing new changes day by day. we have some commitments to clients with a deadline, our system is already live. we have generated few certs in PROD and there are few templates sill pending for approval, how come once day before pull request you have approved and this you can not.

We can not change again and again based on your suggestion. Just 2 days before you dont have sonar integration now you have added rules for that. I can understand you want to maintain the code quality and standards but you can not daily change you guidelines. 

Please approve the pending pull request, for new templates or revised templates we can follow your new guideline rules. If you still want us to make changes then we need to raise this to SSG that this can impact our timeline and there public go live dates.

**Comment by yehjxraymond** [comment]
The problem is poor code quality. 70+% code duplication is laughable. These scanners are in place to sieve out poor quality pull request so that we may focus our time on those that make effort to get it right. 

We did not come up with new rules, these are just good programming practices.

**Comment by ssgwsg-acn** [comment]
yehjxraymond Few certs in SOA are almost looks same, there are some small text changes in the templates in comparison, previously we are sending static type of text in json, that time as per opencert schema we understood that we should not put those data in schema, we have move that part to Templates. Now those common looking cert have different template path. but rest of the functions looks same.  

So now you want us to make that change and make it as common templates?  how ngee Ann Poly deal with duplicated code if we try to follow them we need time to see, make changes and push it.  but our problem is we are running out of time our system is live, we need these templates in opencerts.io

**Comment by yehjxraymond** [comment]
I don't know how can your system be 'live' when the template is not even in. It only reflects poor planning and strategy. 

Running out of time is a poor excuse for poor code quality. Two wrong does not become right, merging bad code in once is our mistake, to do so again it's on us again.  

Seriously, take some time to look at the screenshot rj has put together, it would be a fun spot-the-difference game with the number of differences present. 

We merely automated the process of manually rejecting poor quality code. Good news is that it runs 24/7 and you get instant feedback on your code. 

When Monday come by, we will take a look at all the PRs that are ready for merge. We hope that this is will one of those.

**Comment by ssgwsg-acn** [comment]
The live system currently using the templates which merged before, 3 basic templates. it was very funny that you guys dident have guidelines which you want everyone to follow, seriously you have look on the PR which institutes are raising. if you have clear guidelines how you want things inside your code repo then no one will face these problems.

**Comment by rjchow** [comment]
Didn't realise the amount of garbage people would try to commit into the repo.
Feel free to follow the guidelines as listed in this document https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882

**Comment by ajeetbhatnagar1** [comment]
Hi will try to make the changes, and see if it will reduce the dupicate code. Also will check the Ngee Ann Poly templates how they reduce the duplicate codes.  This sonar test can we run locally?

**Comment by rjchow** [comment]
There's sonarlint for vscode but it doesn't run the full suite unfortunately, will continue looking for a solution there.

**Comment by yehjxraymond** [comment]
Acutally yes you can.

You will need the server: https://www.sonarqube.org/downloads/, just run the command line version will do. That will run a local server at localhost:9000.

Then to create the report you will need to run the scanner:https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner. Run the scanner in the directory where opencerts-website is and you will get the full report in the local server.

**Comment by ssgwsg-acn** [comment]
Refactoring all the templates for duplicate code

**Pull request closed without merging**
