### PR TITLE
Added new templates and registered the institute in registry.json file

### PR DESCRIPTION
**Pull request by ncsblockchain**
---
name: Certificate Template Addition
about: This is the workflow for requesting new certificate templates to be added to
  the OpenCerts repository
title: "[New Template]"
labels: new template
assignees: ''

---

# Pull Request Guidelines for Adding Certificate Templates
This document is a work in progress but here are some basic checks. As these are only basic guidelines, meeting the below doesn't indicate there will be no issues with your pull request.

### Certificate Template 
- [x] No more than 5 templates or 25 added/modified files in the pull request
- [x] Integration test for each template that checks that the correct rendering is done given a sample certificate
- [x] Sample certificate file included for each template, located alongside the integration test for each template
- [x] Sample certificates must obviously be a sample certificate
  - [x] Obviously fictitious name
  - [x] Obviously sample signatory images
- [x] No fixed-size raster images as part of certificate layout
- [x] Mobile responsive design
- [x] Date parsing should be localised to template author's timezone
- [x] Webpack chunking code is correct
  - [x] Has chunking code
  - [x] Same chunking code as the other certificates belonging to that institute
- [x] Certificate Store Addresses have been updated
  - [x] Template Whitelist
  - [x] Registry
- [x] Template should not be using resources(images etc.) on the website outside of their own folder (e.g institute logo shouldn't be used from /static because there's no guarantee it will not change)

### Pre-merge checks

- [x] Ensure that your code has been [rebased](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) on top of latest OpenCerts master
- [x] Linter issues resolved (Run `npm run lint:fix` to see issues)
- [x] `npm run test` passes
- [x] `npm run test:integration` passes
- [x] [Travis Build passes](https://docs.travis-ci.com/user/for-beginners/)

### CODE REVIEW

**Comment by yehjxraymond** [comment]
Also noticed that your files naming is not using camelcase, you might want to consider that, it will be easier to read for you.

**Comment by ncsblockchain** [comment]
Hi,
"Travis-ci" test is in "expected" state for more than an hour now.
Is that an expected behavior or should we need to do anything from our side?
Kindly help.
Thanks!

**Comment by ncsblockchain** [comment]
Hi,

Kindly merge the templates into the master branch.

Thanks !!

**Comment by rjchow** [comment]
Please submit your application to be added to the registry using this form: https://form.gov.sg/5cd5141c02d207001007e322

**Comment by yehjxraymond** [comment]
Closing due to inactivity and also the templates have moved to legacy templates

**Pull request closed without merging**
