### PR TITLE
 SIT-Updated template to include border-20190109-1

### PR DESCRIPTION
**Pull request by erwinsg**
SIT-Updated template to include border-20190109-1

### CODE REVIEW

**Comment by erwinsg** [comment]
hi Rui Jie, Raymond,

Can assist to verify the template?
Thank you.

**Comment by rjchow** [comment]
Can you do this to sync your fork up to our latest version so that the commit history isn't full of duplicate commits?

1. https://help.github.com/articles/configuring-a-remote-for-a-fork/ (the remote repository to use is ours, so https://github.com/opencerts/opencerts-website.git)
2. https://help.github.com/articles/syncing-a-fork/

**Comment by erwinsg** [comment]
Hi Rui Jie,

Is it okay now?

**Comment by rjchow** [comment]
ok looks good, do that next time before you start development and you won't have messy merge conflicts :-)

**Comment by erwinsg** [comment]
ok noted. Thanks again for your help.

**Pull request merged**
